### ISSUE TITLE
Traer traer la información por tuplas con columnas dinámicas KT

### ISSUE THREAD

**Issue by Jacobo0312** [PerficientBootcampStudents/rules-engine-back-kt#2]

**Comment by ArturoDiaz02** [comment]
Feature: Get bring the information by tuples
[Commit](https://github.com/PerficientBootcampStudents/rules-engine-back-kt/commit/04129e3588ce796f3548e2f3124004741dabc8d9)

**Comment by ArturoDiaz02** [comment]
Refactor: Response Table JSON
[Commit](https://github.com/PerficientBootcampStudents/rules-engine-back-kt/commit/45e4379d4e8c2e2aac804e06c24901eada867492)
